apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msa-orderbook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/CoinWing/Infrastructure
    path: kustomize/msa-orderbook
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: cowing-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true