replicaCount: 2

image:
  repository: ghcr.io/coinwing/cowing-msa-auth
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 700Mi 

env:
  - name: REDIS_HOST
    value: "msa-auth-redis"
  - name: REDIS_PORT
    value: "6379"
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: redis-secret
        key: redis-password
  - name: DB_URL
    value: "jdbc:mariadb://common-mariadb:3306/cowingDB"
  - name: DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: mardiadb-secret
        key: username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mardiadb-secret
        key: password
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: jwt-secret
        key: jwt-secret
  - name: ACCESS_TOKEN_EXPIRE
    value: "86400000"
  - name: REFRESH_TOKEN_EXPIRE
    value: "172800000"

imagePullSecrets:
  - name: ghcr-login-secret
