apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - templates/deployment.yaml
  - templates/service.yaml

images:
  - name: ghcr.io/coinwing/Cowing-msa-auth
    newTag: latest
