spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

services:
  msa-auth:
    enabled: true
    repoURL: https://github.com/CoinWing/Cowing-msa-auth
    path: services/msa-auth
    targetRevision: main
  msa-broadcaster:
    enabled: true
    repoURL: https://github.com/CoinWing/Cowing-msa-broadcaster
    path: services/msa-broadcaster
    targetRevision: main
  msa-front:
    enabled: true
    repoURL: https://github.com/CoinWing/front-service
    path: services/msa-front
    targetRevision: main
  msa-orderbook:
    enabled: true
    repoURL: https://github.com/CoinWing/Cowing-msa-orderbook
    path: services/msa-orderbook
    targetRevision: main
  msa-trade:
    enabled: true
    repoURL: https://github.com/CoinWing/Cowing-msa-trading
    path: services/msa-trade
    targetRevision: main
