apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msa-auth
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zzdh8/argocd.git
    targetRevision: main
    path: argocd/apps/chart
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.repository
          value: ghcr.io/coinwing/msa-auth
        - name: image.tag
          value: latest
  destination:
    server: https://kubernetes.default.svc 
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
        - CreateNamespace=true
