apiVersion: v1
kind: Service
metadata:
  name: msa-orderbook
  namespace: cowing-prod
spec:
  selector:
    app: msa-orderbook
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP