apiVersion: v1
kind: Service
metadata:
  name: msa-auth
  namespace: cowing-prod
spec:
  selector:
    app: msa-auth
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP